# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-11 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporter', '0002_counties'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counties',
        ),
    ]
